#import "../fragment/repository.gql"

query user($login: String!, $last: Int!) {
  user(login: $login) {
    repositories(last: $last) {
      nodes {
        ...repository
      }
      totalCount
    }
  }
}
